name: Run Tests on Release

on: push
# optional sinnvoll: auch PRs prüfen
# on:
#   push:
#   pull_request:

permissions:
  contents: read
  id-token: write   # << nötig für OIDC

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Run Jest tests (with coverage)
        run: npm run test:coverage:src

      - name: Upload coverage to Codecov (OIDC)
        uses: codecov/codecov-action@v5
        with:
          use_oidc: true
          files: ./coverage/lcov.info      # Jest legt diese Datei standardmäßig an
          fail_ci_if_error: true
          flags: unittests
        # optional: auch hochladen, wenn Tests fehlschlagen
        # if: ${{ always() }}